model_list:
  - model_name: "qwen3"
    litellm_params:
      model: "ollama/qwen3"
      api_base: "http://192.168.1.10:11434"
  
  - model_name: "llama3"
    litellm_params:
      model: "ollama/llama3"
      api_base: "http://192.168.1.10:11434"

litellm_settings:
  drop_params: true
  request_timeout: 600
  num_retries: 3
